spring.application.name=backend
server.port=8080

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.data.mongodb.uri=mongodb+srv://shailavisrivastava977_db_user:Matra04@cluster0.usvsonz.mongodb.net/lmsdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=lmsdb

jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:your-cloud-name}
cloudinary.api-key=${CLOUDINARY_API_KEY:your-api-key}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:your-api-secret}
cloudinary.folder=cyvanta_lms
file.upload-dir=uploads

jitsi.domain=${JITSI_DOMAIN:meet.jit.si}
jitsi.app-id=${JITSI_APP_ID:my-jitsi-app-id}
jitsi.app-secret=${JITSI_APP_SECRET:my-jitsi-super-secret-key-that-should-be-long-enough}
